/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface BasePlayers {
  puuid: string | null;
  region: string;
}

export interface SeenGames {
  match_id: string | null;
}

export interface DB {
  base_players: BasePlayers;
  seen_games: SeenGames;
}
